"""create favorites table

Revision ID: ce25e55301c0
Revises: fc2c30f435ed
Create Date: 2026-07-25 17:50:24.919630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce25e55301c0'
down_revision: Union[str, Sequence[str], None] = 'fc2c30f435ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('thumbnail_id', sa.Integer(), nullable=False),
    sa.Column('favorited_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['thumbnail_id'], ['thumbnails.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'thumbnail_id', name='uq_user_thumbnail_favorite')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites')
    # ### end Alembic commands ###
